version: "2"

run:
  build-tags:
    - integration

linters:
  enable:
    - errcheck
    - govet
    - sqlclosecheck
    - rowserrcheck

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

    govet:
      enable:
        - atomic
        - bools
        - buildtag
        - errorsas
        - nilfunc
        - printf

    gosec:
      excludes:
        - G101
        - G104
        - G204
        - G304
        - G306
        - G404
        - G501
        - G505

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
