// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/prefeitura-rio/app-go-api/internal/auth"
	"github.com/prefeitura-rio/app-go-api/internal/cache"
	"github.com/prefeitura-rio/app-go-api/internal/clients"
	"github.com/prefeitura-rio/app-go-api/internal/config"
	"github.com/prefeitura-rio/app-go-api/internal/handlers/v1"
	empregabilidade3 "github.com/prefeitura-rio/app-go-api/internal/handlers/v1/empregabilidade"
	"github.com/prefeitura-rio/app-go-api/internal/repository"
	"github.com/prefeitura-rio/app-go-api/internal/repository/empregabilidade"
	"github.com/prefeitura-rio/app-go-api/internal/services"
	empregabilidade2 "github.com/prefeitura-rio/app-go-api/internal/services/empregabilidade"
	"github.com/prefeitura-rio/app-go-api/internal/wire/providers"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeCategoriaContainer wires up Categorias domain for proof-of-concept
func InitializeCategoriaContainer(cfg *config.AppConfig) (*CategoriaContainer, error) {
	db, err := providers.ProvideDatabase(cfg)
	if err != nil {
		return nil, err
	}
	categoriaRepositoryInterface := providers.ProvideCategoriaRepository(db)
	categoriaService := providers.ProvideCategoriaService(categoriaRepositoryInterface)
	categoriaHandler := v1.NewCategoriaHandler(categoriaService)
	categoriaContainer := &CategoriaContainer{
		DB:               db,
		Config:           cfg,
		CategoriaHandler: categoriaHandler,
	}
	return categoriaContainer, nil
}

// InitializeApplication wires up the full application container
func InitializeApplication(cfg *config.AppConfig) (*ApplicationContainer, error) {
	db, err := providers.ProvideDatabase(cfg)
	if err != nil {
		return nil, err
	}
	client := providers.ProvideRedisClient(cfg)
	rmiClient := providers.ProvideRMIClient(cfg)
	serviceAccountTokenManager := providers.ProvideServiceAccountTokenManager(cfg)
	dataRelayClient := providers.ProvideDataRelayClient(cfg)
	referenceCaches := providers.ProvideReferenceCaches(client)
	legalEntitiesCache := providers.ProvideLegalEntitiesCache(client)
	courseCache := providers.ProvideCourseCache(client)
	cursoRepository := providers.ProvideCursoRepository(db)
	inscricaoRepository := providers.ProvideInscricaoRepository(db)
	empregoRepository := providers.ProvideEmpregoRepository(db)
	acessibilidadeRepository := providers.ProvideAcessibilidadeRepository(db)
	categoriaRepositoryInterface := providers.ProvideCategoriaRepository(db)
	escolaridadeRepository := providers.ProvideEscolaridadeRepository(db)
	empresaRepository := providers.ProvideEmpresaRepository(db)
	instituicaoRepository := providers.ProvideInstituicaoRepository(db)
	jobRepository := providers.ProvideJobRepository(db)
	oportunidadeMEIRepository := providers.ProvideOportunidadeMEIRepository(db)
	propostaMEIRepository := providers.ProvidePropostaMEIRepository(db)
	orgaoSnapshotRepository := providers.ProvideOrgaoSnapshotRepository(db)
	citizenSnapshotRepository := providers.ProvideCitizenSnapshotRepository(db)
	regimeContratacaoRepository := providers.ProvideEmpRegimeContratacaoRepository(db)
	modeloTrabalhoRepository := providers.ProvideEmpModeloTrabalhoRepository(db)
	tipoPCDRepository := providers.ProvideEmpTipoPCDRepository(db)
	idiomaRepository := providers.ProvideEmpIdiomaRepository(db)
	nivelIdiomaRepository := providers.ProvideEmpNivelIdiomaRepository(db)
	empregabilidadeEscolaridadeRepository := providers.ProvideEmpEscolaridadeRepository(db)
	tipoConquistaRepository := providers.ProvideEmpTipoConquistaRepository(db)
	situacaoAtualRepository := providers.ProvideEmpSituacaoAtualRepository(db)
	disponibilidadeRepository := providers.ProvideEmpDisponibilidadeRepository(db)
	empregabilidadeEmpresaRepository := providers.ProvideEmpEmpresaRepository(db)
	vagaRepository := providers.ProvideEmpVagaRepository(db)
	etapaRepository := providers.ProvideEmpEtapaRepository(db)
	candidaturaRepository := providers.ProvideEmpCandidaturaRepository(db)
	curriculoRepository := providers.ProvideEmpCurriculoRepository(db)
	onboardingRepository := providers.ProvideEmpOnboardingRepository(db)
	termosUsoRepository := providers.ProvideEmpTermosUsoRepository(db)
	cursoService := providers.ProvideCursoService(cursoRepository)
	emailNotificationService := providers.ProvideEmailNotificationService(dataRelayClient, cursoRepository, orgaoSnapshotRepository, citizenSnapshotRepository, cfg)
	inscricaoService := providers.ProvideInscricaoService(inscricaoRepository, cursoRepository, citizenSnapshotRepository, emailNotificationService, cfg)
	empregoService := providers.ProvideEmpregoService(empregoRepository)
	acessibilidadeService := providers.ProvideAcessibilidadeService(acessibilidadeRepository)
	categoriaService := providers.ProvideCategoriaService(categoriaRepositoryInterface)
	escolaridadeService := providers.ProvideEscolaridadeService(escolaridadeRepository)
	empresaService := providers.ProvideEmpresaService(empresaRepository)
	instituicaoService := providers.ProvideInstituicaoService(instituicaoRepository)
	jobService := providers.ProvideJobService(jobRepository)
	oportunidadeMEIService := providers.ProvideOportunidadeMEIService(oportunidadeMEIRepository)
	cnaeValidationService := providers.ProvideCNAEValidationService(rmiClient, legalEntitiesCache)
	contactInfoService := providers.ProvideContactInfoService(rmiClient, serviceAccountTokenManager, client, cfg)
	propostaMEIService := providers.ProvidePropostaMEIService(propostaMEIRepository, oportunidadeMEIRepository, cnaeValidationService, contactInfoService)
	regimeContratacaoService := providers.ProvideEmpRegimeContratacaoService(regimeContratacaoRepository)
	modeloTrabalhoService := providers.ProvideEmpModeloTrabalhoService(modeloTrabalhoRepository)
	tipoPCDService := providers.ProvideEmpTipoPCDService(tipoPCDRepository)
	idiomaService := providers.ProvideEmpIdiomaService(idiomaRepository)
	nivelIdiomaService := providers.ProvideEmpNivelIdiomaService(nivelIdiomaRepository)
	empregabilidadeEscolaridadeService := providers.ProvideEmpEscolaridadeService(empregabilidadeEscolaridadeRepository)
	tipoConquistaService := providers.ProvideEmpTipoConquistaService(tipoConquistaRepository)
	situacaoAtualService := providers.ProvideEmpSituacaoAtualService(situacaoAtualRepository)
	disponibilidadeService := providers.ProvideEmpDisponibilidadeService(disponibilidadeRepository)
	empregabilidadeEmpresaService := providers.ProvideEmpEmpresaService(empregabilidadeEmpresaRepository)
	vagaService := providers.ProvideEmpVagaService(vagaRepository, empregabilidadeEmpresaRepository, candidaturaRepository)
	etapaService := providers.ProvideEmpEtapaService(etapaRepository)
	curriculoService := providers.ProvideEmpCurriculoService(curriculoRepository)
	candidaturaService := providers.ProvideEmpCandidaturaService(candidaturaRepository, vagaRepository, curriculoService, citizenSnapshotRepository)
	onboardingService := providers.ProvideEmpOnboardingService(onboardingRepository)
	termosUsoService := providers.ProvideEmpTermosUsoService(termosUsoRepository)
	cnpjConsultaService := providers.ProvideEmpCNPJConsultaService(rmiClient, serviceAccountTokenManager)
	empregoHandler := providers.ProvideEmpregoHandler(empregoService)
	acessibilidadeHandler := providers.ProvideAcessibilidadeHandler(acessibilidadeService, referenceCaches)
	categoriaHandler := providers.ProvideCategoriaHandlerWithCache(categoriaService, referenceCaches)
	empresaHandler := providers.ProvideEmpresaHandler(empresaService)
	escolaridadeHandler := providers.ProvideEscolaridadeHandler(escolaridadeService, referenceCaches)
	instituicaoHandler := providers.ProvideInstituicaoHandler(instituicaoService)
	inscricaoHandler := providers.ProvideInscricaoHandler(inscricaoService, jobService, cursoRepository)
	courseHandler := providers.ProvideCourseHandler(cursoService, inscricaoService, cursoRepository, courseCache)
	jobHandler := providers.ProvideJobHandler(jobService)
	oportunidadeMEIHandler := providers.ProvideOportunidadeMEIHandler(oportunidadeMEIService)
	propostaMEIHandler := providers.ProvidePropostaMEIHandler(propostaMEIService, cnaeValidationService, cfg)
	typesenseHandler := providers.ProvideTypesenseHandler()
	regimeContratacaoHandler := providers.ProvideEmpRegimeContratacaoHandler(regimeContratacaoService)
	modeloTrabalhoHandler := providers.ProvideEmpModeloTrabalhoHandler(modeloTrabalhoService)
	tipoPCDHandler := providers.ProvideEmpTipoPCDHandler(tipoPCDService)
	idiomaHandler := providers.ProvideEmpIdiomaHandler(idiomaService)
	nivelIdiomaHandler := providers.ProvideEmpNivelIdiomaHandler(nivelIdiomaService)
	empregabilidadeEscolaridadeHandler := providers.ProvideEmpEscolaridadeHandler(empregabilidadeEscolaridadeService)
	tipoConquistaHandler := providers.ProvideEmpTipoConquistaHandler(tipoConquistaService)
	situacaoAtualHandler := providers.ProvideEmpSituacaoAtualHandler(situacaoAtualService)
	disponibilidadeHandler := providers.ProvideEmpDisponibilidadeHandler(disponibilidadeService)
	empregabilidadeEmpresaHandler := providers.ProvideEmpEmpresaHandler(empregabilidadeEmpresaService, cnpjConsultaService)
	vagaHandler := providers.ProvideEmpVagaHandler(vagaService)
	etapaHandler := providers.ProvideEmpEtapaHandler(etapaService)
	candidaturaHandler := providers.ProvideEmpCandidaturaHandler(candidaturaService)
	curriculoHandler := providers.ProvideEmpCurriculoHandler(curriculoService)
	onboardingHandler := providers.ProvideEmpOnboardingHandler(onboardingService)
	termosUsoHandler := providers.ProvideEmpTermosUsoHandler(termosUsoService)
	applicationContainer := &ApplicationContainer{
		DB:                          db,
		Config:                      cfg,
		RedisClient:                 client,
		RMIClient:                   rmiClient,
		TokenManager:                serviceAccountTokenManager,
		DataRelayClient:             dataRelayClient,
		ReferenceCaches:             referenceCaches,
		LegalEntitiesCache:          legalEntitiesCache,
		CourseCache:                 courseCache,
		CursoRepo:                   cursoRepository,
		InscricaoRepo:               inscricaoRepository,
		EmpregoRepo:                 empregoRepository,
		AcessibilidadeRepo:          acessibilidadeRepository,
		CategoriaRepo:               categoriaRepositoryInterface,
		EscolaridadeRepo:            escolaridadeRepository,
		EmpresaRepo:                 empresaRepository,
		InstituicaoRepo:             instituicaoRepository,
		JobRepo:                     jobRepository,
		OportunidadeMEIRepo:         oportunidadeMEIRepository,
		PropostaMEIRepo:             propostaMEIRepository,
		OrgaoSnapshotRepo:           orgaoSnapshotRepository,
		CitizenSnapshotRepo:         citizenSnapshotRepository,
		EmpRegimeContratacaoRepo:    regimeContratacaoRepository,
		EmpModeloTrabalhoRepo:       modeloTrabalhoRepository,
		EmpTipoPCDRepo:              tipoPCDRepository,
		EmpIdiomaRepo:               idiomaRepository,
		EmpNivelIdiomaRepo:          nivelIdiomaRepository,
		EmpEscolaridadeRepo:         empregabilidadeEscolaridadeRepository,
		EmpTipoConquistaRepo:        tipoConquistaRepository,
		EmpSituacaoAtualRepo:        situacaoAtualRepository,
		EmpDisponibilidadeRepo:      disponibilidadeRepository,
		EmpEmpresaRepo:              empregabilidadeEmpresaRepository,
		EmpVagaRepo:                 vagaRepository,
		EmpEtapaRepo:                etapaRepository,
		EmpCandidaturaRepo:          candidaturaRepository,
		EmpCurriculoRepo:            curriculoRepository,
		EmpOnboardingRepo:           onboardingRepository,
		EmpTermosUsoRepo:            termosUsoRepository,
		CursoService:                cursoService,
		InscricaoService:            inscricaoService,
		EmpregoService:              empregoService,
		AcessibilidadeService:       acessibilidadeService,
		CategoriaService:            categoriaService,
		EscolaridadeService:         escolaridadeService,
		EmpresaService:              empresaService,
		InstituicaoService:          instituicaoService,
		JobService:                  jobService,
		OportunidadeMEIService:      oportunidadeMEIService,
		PropostaMEIService:          propostaMEIService,
		CNAEValidationService:       cnaeValidationService,
		ContactInfoService:          contactInfoService,
		EmailNotificationService:    emailNotificationService,
		EmpRegimeContratacaoService: regimeContratacaoService,
		EmpModeloTrabalhoService:    modeloTrabalhoService,
		EmpTipoPCDService:           tipoPCDService,
		EmpIdiomaService:            idiomaService,
		EmpNivelIdiomaService:       nivelIdiomaService,
		EmpEscolaridadeService:      empregabilidadeEscolaridadeService,
		EmpTipoConquistaService:     tipoConquistaService,
		EmpSituacaoAtualService:     situacaoAtualService,
		EmpDisponibilidadeService:   disponibilidadeService,
		EmpEmpresaService:           empregabilidadeEmpresaService,
		EmpVagaService:              vagaService,
		EmpEtapaService:             etapaService,
		EmpCurriculoService:         curriculoService,
		EmpCandidaturaService:       candidaturaService,
		EmpOnboardingService:        onboardingService,
		EmpTermosUsoService:         termosUsoService,
		EmpCNPJConsultaService:      cnpjConsultaService,
		EmpregoHandler:              empregoHandler,
		AcessibilidadeHandler:       acessibilidadeHandler,
		CategoriaHandler:            categoriaHandler,
		EmpresaHandler:              empresaHandler,
		EscolaridadeHandler:         escolaridadeHandler,
		InstituicaoHandler:          instituicaoHandler,
		InscricaoHandler:            inscricaoHandler,
		CourseHandler:               courseHandler,
		JobHandler:                  jobHandler,
		OportunidadeMEIHandler:      oportunidadeMEIHandler,
		PropostaMEIHandler:          propostaMEIHandler,
		TypesenseHandler:            typesenseHandler,
		EmpRegimeContratacaoHandler: regimeContratacaoHandler,
		EmpModeloTrabalhoHandler:    modeloTrabalhoHandler,
		EmpTipoPCDHandler:           tipoPCDHandler,
		EmpIdiomaHandler:            idiomaHandler,
		EmpNivelIdiomaHandler:       nivelIdiomaHandler,
		EmpEscolaridadeHandler:      empregabilidadeEscolaridadeHandler,
		EmpTipoConquistaHandler:     tipoConquistaHandler,
		EmpSituacaoAtualHandler:     situacaoAtualHandler,
		EmpDisponibilidadeHandler:   disponibilidadeHandler,
		EmpEmpresaHandler:           empregabilidadeEmpresaHandler,
		EmpVagaHandler:              vagaHandler,
		EmpEtapaHandler:             etapaHandler,
		EmpCandidaturaHandler:       candidaturaHandler,
		EmpCurriculoHandler:         curriculoHandler,
		EmpOnboardingHandler:        onboardingHandler,
		EmpTermosUsoHandler:         termosUsoHandler,
	}
	return applicationContainer, nil
}

// wire.go:

// ApplicationContainer holds all wired components for the full application
type ApplicationContainer struct {
	DB     *gorm.DB
	Config *config.AppConfig

	// Infrastructure
	RedisClient     *redis.Client
	RMIClient       *clients.RMIClient
	TokenManager    *auth.ServiceAccountTokenManager
	DataRelayClient *clients.DataRelayClient

	// Caches
	ReferenceCaches    *providers.ReferenceCaches
	LegalEntitiesCache *cache.LegalEntitiesCache
	CourseCache        *cache.CourseCache

	// Core Repositories
	CursoRepo           *repository.CursoRepository
	InscricaoRepo       *repository.InscricaoRepository
	EmpregoRepo         *repository.EmpregoRepository
	AcessibilidadeRepo  *repository.AcessibilidadeRepository
	CategoriaRepo       repository.CategoriaRepositoryInterface
	EscolaridadeRepo    *repository.EscolaridadeRepository
	EmpresaRepo         *repository.EmpresaRepository
	InstituicaoRepo     *repository.InstituicaoRepository
	JobRepo             *repository.JobRepository
	OportunidadeMEIRepo *repository.OportunidadeMEIRepository
	PropostaMEIRepo     *repository.PropostaMEIRepository
	OrgaoSnapshotRepo   *repository.OrgaoSnapshotRepository
	CitizenSnapshotRepo *repository.CitizenSnapshotRepository

	// Empregabilidade Repositories
	EmpRegimeContratacaoRepo *empregabilidade.RegimeContratacaoRepository
	EmpModeloTrabalhoRepo    *empregabilidade.ModeloTrabalhoRepository
	EmpTipoPCDRepo           *empregabilidade.TipoPCDRepository
	EmpIdiomaRepo            *empregabilidade.IdiomaRepository
	EmpNivelIdiomaRepo       *empregabilidade.NivelIdiomaRepository
	EmpEscolaridadeRepo      *empregabilidade.EscolaridadeRepository
	EmpTipoConquistaRepo     *empregabilidade.TipoConquistaRepository
	EmpSituacaoAtualRepo     *empregabilidade.SituacaoAtualRepository
	EmpDisponibilidadeRepo   *empregabilidade.DisponibilidadeRepository
	EmpEmpresaRepo           *empregabilidade.EmpresaRepository
	EmpVagaRepo              *empregabilidade.VagaRepository
	EmpEtapaRepo             *empregabilidade.EtapaRepository
	EmpCandidaturaRepo       *empregabilidade.CandidaturaRepository
	EmpCurriculoRepo         *empregabilidade.CurriculoRepository
	EmpOnboardingRepo        *empregabilidade.OnboardingRepository
	EmpTermosUsoRepo         *empregabilidade.TermosUsoRepository

	// Core Services
	CursoService             *services.CursoService
	InscricaoService         *services.InscricaoService
	EmpregoService           *services.EmpregoService
	AcessibilidadeService    *services.AcessibilidadeService
	CategoriaService         *services.CategoriaService
	EscolaridadeService      *services.EscolaridadeService
	EmpresaService           *services.EmpresaService
	InstituicaoService       *services.InstituicaoService
	JobService               *services.JobService
	OportunidadeMEIService   *services.OportunidadeMEIService
	PropostaMEIService       *services.PropostaMEIService
	CNAEValidationService    *services.CNAEValidationService
	ContactInfoService       *services.ContactInfoService
	EmailNotificationService *services.EmailNotificationService

	// Empregabilidade Services
	EmpRegimeContratacaoService *empregabilidade2.RegimeContratacaoService
	EmpModeloTrabalhoService    *empregabilidade2.ModeloTrabalhoService
	EmpTipoPCDService           *empregabilidade2.TipoPCDService
	EmpIdiomaService            *empregabilidade2.IdiomaService
	EmpNivelIdiomaService       *empregabilidade2.NivelIdiomaService
	EmpEscolaridadeService      *empregabilidade2.EscolaridadeService
	EmpTipoConquistaService     *empregabilidade2.TipoConquistaService
	EmpSituacaoAtualService     *empregabilidade2.SituacaoAtualService
	EmpDisponibilidadeService   *empregabilidade2.DisponibilidadeService
	EmpEmpresaService           *empregabilidade2.EmpresaService
	EmpVagaService              *empregabilidade2.VagaService
	EmpEtapaService             *empregabilidade2.EtapaService
	EmpCurriculoService         *empregabilidade2.CurriculoService
	EmpCandidaturaService       *empregabilidade2.CandidaturaService
	EmpOnboardingService        *empregabilidade2.OnboardingService
	EmpTermosUsoService         *empregabilidade2.TermosUsoService
	EmpCNPJConsultaService      *empregabilidade2.CNPJConsultaService

	// Core Handlers
	EmpregoHandler         *v1.EmpregoHandler
	AcessibilidadeHandler  *v1.AcessibilidadeHandler
	CategoriaHandler       *v1.CategoriaHandler
	EmpresaHandler         *v1.EmpresaHandler
	EscolaridadeHandler    *v1.EscolaridadeHandler
	InstituicaoHandler     *v1.InstituicaoHandler
	InscricaoHandler       *v1.InscricaoHandler
	CourseHandler          *v1.CourseHandler
	JobHandler             *v1.JobHandler
	OportunidadeMEIHandler *v1.OportunidadeMEIHandler
	PropostaMEIHandler     *v1.PropostaMEIHandler
	TypesenseHandler       *v1.TypesenseHandler

	// Empregabilidade Handlers
	EmpRegimeContratacaoHandler *empregabilidade3.RegimeContratacaoHandler
	EmpModeloTrabalhoHandler    *empregabilidade3.ModeloTrabalhoHandler
	EmpTipoPCDHandler           *empregabilidade3.TipoPCDHandler
	EmpIdiomaHandler            *empregabilidade3.IdiomaHandler
	EmpNivelIdiomaHandler       *empregabilidade3.NivelIdiomaHandler
	EmpEscolaridadeHandler      *empregabilidade3.EscolaridadeHandler
	EmpTipoConquistaHandler     *empregabilidade3.TipoConquistaHandler
	EmpSituacaoAtualHandler     *empregabilidade3.SituacaoAtualHandler
	EmpDisponibilidadeHandler   *empregabilidade3.DisponibilidadeHandler
	EmpEmpresaHandler           *empregabilidade3.EmpresaHandler
	EmpVagaHandler              *empregabilidade3.VagaHandler
	EmpEtapaHandler             *empregabilidade3.EtapaHandler
	EmpCandidaturaHandler       *empregabilidade3.CandidaturaHandler
	EmpCurriculoHandler         *empregabilidade3.CurriculoHandler
	EmpOnboardingHandler        *empregabilidade3.OnboardingHandler
	EmpTermosUsoHandler         *empregabilidade3.TermosUsoHandler
}

// CategoriaContainer holds wired components for Categorias proof-of-concept
type CategoriaContainer struct {
	DB               *gorm.DB
	Config           *config.AppConfig
	CategoriaHandler *v1.CategoriaHandler
}

var DatabaseSet = wire.NewSet(providers.ProvideDatabase)

var InfrastructureSet = wire.NewSet(providers.ProvideDatabase, providers.ProvideRedisClient, providers.ProvideRMIClient, providers.ProvideDataRelayClient, providers.ProvideServiceAccountTokenManager)

var CacheSet = wire.NewSet(providers.ProvideLegalEntitiesCache, providers.ProvideReferenceCaches, providers.ProvideCourseCache)

var CoreRepositorySet = wire.NewSet(providers.ProvideCategoriaRepository, providers.ProvideCursoRepository, providers.ProvideInscricaoRepository, providers.ProvideEmpregoRepository, providers.ProvideAcessibilidadeRepository, providers.ProvideEscolaridadeRepository, providers.ProvideEmpresaRepository, providers.ProvideInstituicaoRepository, providers.ProvideJobRepository, providers.ProvideOportunidadeMEIRepository, providers.ProvidePropostaMEIRepository, providers.ProvideOrgaoSnapshotRepository, providers.ProvideCitizenSnapshotRepository)

var EmpRepositorySet = wire.NewSet(providers.ProvideEmpRegimeContratacaoRepository, providers.ProvideEmpModeloTrabalhoRepository, providers.ProvideEmpTipoPCDRepository, providers.ProvideEmpIdiomaRepository, providers.ProvideEmpNivelIdiomaRepository, providers.ProvideEmpEscolaridadeRepository, providers.ProvideEmpTipoConquistaRepository, providers.ProvideEmpSituacaoAtualRepository, providers.ProvideEmpDisponibilidadeRepository, providers.ProvideEmpEmpresaRepository, providers.ProvideEmpVagaRepository, providers.ProvideEmpEtapaRepository, providers.ProvideEmpCandidaturaRepository, providers.ProvideEmpCurriculoRepository, providers.ProvideEmpOnboardingRepository, providers.ProvideEmpTermosUsoRepository)

var CoreServiceSet = wire.NewSet(providers.ProvideCategoriaService, providers.ProvideCursoService, providers.ProvideEmpregoService, providers.ProvideAcessibilidadeService, providers.ProvideEscolaridadeService, providers.ProvideEmpresaService, providers.ProvideInstituicaoService, providers.ProvideJobService, providers.ProvideOportunidadeMEIService, providers.ProvideCNAEValidationService, providers.ProvideContactInfoService, providers.ProvideEmailNotificationService, providers.ProvideInscricaoService, providers.ProvidePropostaMEIService)

var EmpServiceSet = wire.NewSet(providers.ProvideEmpRegimeContratacaoService, providers.ProvideEmpModeloTrabalhoService, providers.ProvideEmpTipoPCDService, providers.ProvideEmpIdiomaService, providers.ProvideEmpNivelIdiomaService, providers.ProvideEmpEscolaridadeService, providers.ProvideEmpTipoConquistaService, providers.ProvideEmpSituacaoAtualService, providers.ProvideEmpDisponibilidadeService, providers.ProvideEmpEmpresaService, providers.ProvideEmpVagaService, providers.ProvideEmpEtapaService, providers.ProvideEmpCurriculoService, providers.ProvideEmpCandidaturaService, providers.ProvideEmpOnboardingService, providers.ProvideEmpTermosUsoService, providers.ProvideEmpCNPJConsultaService)

var CoreHandlerSet = wire.NewSet(providers.ProvideEmpregoHandler, providers.ProvideAcessibilidadeHandler, providers.ProvideCategoriaHandlerWithCache, providers.ProvideEmpresaHandler, providers.ProvideEscolaridadeHandler, providers.ProvideInstituicaoHandler, providers.ProvideInscricaoHandler, providers.ProvideCourseHandler, providers.ProvideJobHandler, providers.ProvideOportunidadeMEIHandler, providers.ProvidePropostaMEIHandler, providers.ProvideTypesenseHandler)

var EmpHandlerSet = wire.NewSet(providers.ProvideEmpRegimeContratacaoHandler, providers.ProvideEmpModeloTrabalhoHandler, providers.ProvideEmpTipoPCDHandler, providers.ProvideEmpIdiomaHandler, providers.ProvideEmpNivelIdiomaHandler, providers.ProvideEmpEscolaridadeHandler, providers.ProvideEmpTipoConquistaHandler, providers.ProvideEmpSituacaoAtualHandler, providers.ProvideEmpDisponibilidadeHandler, providers.ProvideEmpEmpresaHandler, providers.ProvideEmpVagaHandler, providers.ProvideEmpEtapaHandler, providers.ProvideEmpCandidaturaHandler, providers.ProvideEmpCurriculoHandler, providers.ProvideEmpOnboardingHandler, providers.ProvideEmpTermosUsoHandler)

// Legacy set kept for backward compatibility with the Categorias POC
var CategoriaSet = wire.NewSet(providers.ProvideCategoriaRepository, providers.ProvideCategoriaService, wire.Bind(new(services.CategoriaServiceInterface), new(*services.CategoriaService)), v1.NewCategoriaHandler)
