---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go
          image: ghcr.io/prefeitura-rio/app-go-api:stable
          ports:
            - containerPort: 8080
          env:
            - name: TRACING_ENABLED
              value: "true"
            - name: TRACING_ENDPOINT
              value: "signoz-otel-collector.signoz.svc.cluster.local:4317"
            - name: TRACING_SERVICE_NAME
              value: "go"
            - name: TRACING_SERVICE_VERSION
              value: "v1.0.0"
          envFrom:
            - secretRef:
                name: go-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: go
spec:
  selector:
    app: go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
