basePath: /
host: localhost:8081
info:
  contact:
    email: frederico.zolio@prefeitura.rio
    name: API Support
    url: https://iplan.rio
  description: API de serviços para aplicativos da Prefeitura do Rio
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API Go
  version: "1.0"
paths: {}
schemes:
- http
- https
security:
- BearerAuth: []
securityDefinitions:
  BearerAuth:
    description: Autenticação usando token JWT no formato 'Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
