-- +goose Up
-- +goose StatementBegin

-- 1. Criação das tabelas
CREATE TABLE IF NOT EXISTS emp_habilidades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(500) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS area_atuacao (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(500) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS area_atuacao_habilidade (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_habilidade UUID NOT NULL REFERENCES emp_habilidades(id) ON DELETE CASCADE, 
    id_area_atuacao UUID NOT NULL REFERENCES area_atuacao(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_habilidade_area UNIQUE (id_habilidade, id_area_atuacao)
);

-- 2. Inserção massiva de dados

-- 2.1 HABILIDADES
INSERT INTO emp_habilidades (nome) VALUES
('Acabamento'),
('Acabamento artesanal'),
('Acabamento em gesso'),
('Acabamento gráfico'),
('Acompanhamento de alunos'),
('Acompanhamento de pacientes'),
('Aconselhamento'),
('Adaptabilidade tecnológica'),
('Adaptação a diferentes tarefas'),
('Adaptação de conteúdo'),
('Adaptação de linguagem'),
('Administração de banco de dados'),
('Administração de medicamentos'),
('Administração de redes'),
('Adubação e fertilidade'),
('Afinação de instrumentos'),
('Agendamento'),
('Agilidade'),
('Agricultura de precisão'),
('Agronegócio'),
('Ajuste de máquinas'),
('Ajuste de peças'),
('Alimentação e cuidados básicos'),
('Alinhamento e balanceamento'),
('Amor por animais'),
('Anatomia aplicada'),
('Análise comportamental'),
('Análise contábil'),
('Análise de concorrência'),
('Análise de conformidade'),
('Análise de crédito'),
('Análise de cultivos'),
('Análise de custos de frete'),
('Análise de dados'),
('Análise de eficiência'),
('Análise de evidências'),
('Análise de impacto ambiental'),
('Análise de indicadores económicos'),
('Análise de investimentos'),
('Análise de materiais'),
('Análise de metas comerciais'),
('Análise de métricas'),
('Análise de qualidade da água'),
('Análise de riscos'),
('Análise de viabilidade'),
('Análise de vulnerabilidades'),
('Análise financeira'),
('Análise geológica'),
('Análise laboratorial'),
('Análise processual'),
('Análise técnica'),
('Análises laboratoriais'),
('Anúncios online'),
('Aplicativos de entrega'),
('Aplicação de multas e autuações'),
('Apoio emocional'),
('Aprendizado continuo'),
('Apresentação de pratos'),
('Apresentação de projetos'),
('Apresentação de resultados'),
('Apresentação do produto'),
('Apuração de fatos'),
('Argumentação'),
('Argumentação de vendas'),
('Argumentação jurídica'),
('Arquivamento'),
('Articulação política'),
('Atendimento'),
('Atendimento a chamados'),
('Atendimento a chamados técnicos'),
('Atendimento a clientes'),
('Atendimento a familias'),
('Atendimento ao cliente'),
('Atendimento ao hóspede'),
('Atendimento ao paciente'),
('Atendimento ao passageiro'),
('Atendimento ao público'),
('Atendimento ao usuário'),
('Atenção a detalhes')
ON CONFLICT (nome) DO NOTHING;

-- 2.2 ÁREAS DE ATUAÇÃO
INSERT INTO area_atuacao (nome) VALUES
('Confecção de Artefatos de Tecido e Couro'),
('Confecção de Calçados'),
('Confecção de Roupas'),
('Joalheria e Ourivesaria'),
('Marcenaria e Indústria Moveleira'),
('Pintura Predial e Residencial'),
('Artesanato Têxtil e Gráfico'),
('Artesanato em Fibras Naturais'),
('Artesanato'),
('Gesso e Drywall'),
('Produção Gráfica e Impressão'),
('Coordenação Pedagógica e Apoio Escolar'),
('Nutrição'),
('Terapias e Reabilitação'),
('Vida Religiosa'),
('TI (Geral/Outras Especialidades)'),
('Outros Serviços Diversos'),
('Educação Especial e Inclusiva'),
('Redação e Produção de Conteúdo'),
('Tradução e Interpretação'),
('Banco de Dados'),
('Enfermagem'),
('Infraestrutura de TI'),
('Agronomia e Engenharia Agrícola'),
('Luthieria e Instrumentos Musicais'),
('Atendimento ao Público e Recepção'),
('Bombeiros Civis e Salva-Vidas'),
('Caixas e Bilheteiros'),
('Embalagem e Logística de Produção'),
('Entregadores e Motoboys'),
('Garçons e Atendimento em Bares e Restaurantes'),
('Lavanderia e Cuidado de Roupas'),
('Manutenção Mecânica Industrial'),
('Metalurgia e Usinagem'),
('Montagem de Máquinas e Motores'),
('Técnicos em Metalmecânica'),
('Pecuária (Trabalhadores)'),
('Manutenção Eletromecânica'),
('Cuidado de Animais de Estimação'),
('Fisioterapia'),
('Psicologia e Ciências Sociais'),
('Contabilidade'),
('Marketing e Publicidade'),
('Fiscalização e Auditoria Pública'),
('Serviços Bancários e Financeiros'),
('Logística e Transportes (Técnicos e Especialistas)'),
('Matemática, Estatística e Ciência de Dados'),
('Pesquisa Científica'),
('Gestão Industrial e de Operações'),
('Delegacia de Polícia e Inteligência'),
('Perícia Criminal'),
('Engenharia Ambiental'),
('Mercado de Capitais e Investimentos'),
('Finanças e Controladoria'),
('Engenharia Mecânica'),
('Vendas e Comércio (Gestão)'),
('Marketing Digital e Mídias Sociais'),
('Tratamento e Distribuição de Água e Esgoto'),
('Segurança Corporativa e Gestão de Riscos'),
('Pesquisa, Desenvolvimento e Inovação'),
('Cibersegurança'),
('Mineração e Geologia'),
('Engenharia Química'),
('Engenharia de Alimentos'),
('Física, Química e Ciências Naturais'),
('Ministério Público, Magistratura e Defensoria'),
('Engenharia Elétrica e Eletrônica'),
('Engenharia de Materiais e Metalurgia'),
('Biologia e Biomedicina'),
('Bioquímica e Biotecnologia'),
('Técnicos em Diagnóstico por Imagem e Laboratório'),
('Técnicos em Laboratório'),
('Técnicos em Química e Física'),
('Segurança Pública Municipal e Trânsito'),
('Apoio e Cuidados em Saúde'),
('Gastronomia e Culinária'),
('Produção Artesanal de Alimentos'),
('Jornalismo e Mídia'),
('Telemarketing e Televendas'),
('Advocacia e Direito'),
('Serviços Administrativos e Escritório'),
('Política e Administração Pública (Executivo, Legislativo e Judiciário)'),
('Secretariado Executivo'),
('Manutenção Predial (Reparos e Estruturas)'),
('Manutenção Eletroeletrônica'),
('Manutenção Industrial'),
('Manutenção de Equipamentos (Outros)'),
('Manutenção de Máquinas Pesadas e Agrícolas'),
('Telecomunicações e Eletroeletrônica'),
('Técnicos em Mecatrônica e Eletromecânica'),
('Serviços Funerários'),
('Beleza e Estética'),
('Comércio'),
('Design de Interiores'),
('Elétrica Residencial e Predial'),
('Farmácia'),
('Hidráulica e Encanamento'),
('Instalação e Manutenção de Ar-Condicionado'),
('Manutenção Automotiva'),
('Montagem de Móveis'),
('Relojoaria e Instrumentos de Precisão'),
('Turismo, Hotelaria e Eventos'),
('Vendas Ambulantes e a Domicilio'),
('Hotelaria e Hospedagem'),
('Medicina'),
('Odontologia'),
('Técnicos em Saúde'),
('Motoristas de Ônibus e Transporte Coletivo'),
('Atendimento e Fiscalização em Transporte Coletivo'),
('Biblioteconomia e Arquivologia'),
('Correios, Documentação e Arquivo'),
('Guia de Turismo e Condução de Excursões'),
('Portaria e Zeladoria'),
('Suporte Técnico de TI'),
('Celulose e Papel'),
('Cerâmica, Vidro e Materiais de Construção'),
('Couro e Peles'),
('Cultura e Produção de Eventos'),
('Desenho Técnico e Modelagem'),
('Fotografia'),
('Instalação e Manutenção de Redes e Cabos'),
('Limpeza e Conservação de Áreas'),
('Navegação Marítima e Aviação'),
('Operação de Guindastes e Movimentação de Cargas'),
('Operação de Robôs e Equipamentos Especiais'),
('Produção de Alimentos e Bebidas'),
('Produção de Fumo'),
('Segurança Privada e Vigilância'),
('Transporte Aquaviário'),
('Transporte Ferroviário e Metroviário'),
('Têxtil, Vestuário e Calçados'),
('Visual Merchandising e Vitrinismo')
ON CONFLICT (nome) DO NOTHING;

-- 2.3 RELACIONAMENTOS (area_atuacao_habilidade)
INSERT INTO area_atuacao_habilidade (id_habilidade, id_area_atuacao)
SELECT h.id, a.id
FROM (VALUES
    ('Acabamento', 'Confecção de Artefatos de Tecido e Couro'),
    ('Acabamento', 'Confecção de Calçados'),
    ('Acabamento', 'Confecção de Roupas'),
    ('Acabamento', 'Joalheria e Ourivesaria'),
    ('Acabamento', 'Marcenaria e Indústria Moveleira'),
    ('Acabamento', 'Pintura Predial e Residencial'),
    ('Acabamento artesanal', 'Artesanato Têxtil e Gráfico'),
    ('Acabamento artesanal', 'Artesanato em Fibras Naturais'),
    ('Acabamento em gesso', 'Gesso e Drywall'),
    ('Acabamento gráfico', 'Produção Gráfica e Impressão'),
    ('Acompanhamento de alunos', 'Coordenação Pedagógica e Apoio Escolar'),
    ('Acompanhamento de pacientes', 'Nutrição'),
    ('Acompanhamento de pacientes', 'Terapias e Reabilitação'),
    ('Aconselhamento', 'Vida Religiosa'),
    ('Adaptabilidade tecnológica', 'TI (Geral/Outras Especialidades)'),
    ('Adaptação a diferentes tarefas', 'Outros Serviços Diversos'),
    ('Adaptação de conteúdo', 'Educação Especial e Inclusiva'),
    ('Adaptação de linguagem', 'Redação e Produção de Conteúdo'),
    ('Adaptação de linguagem', 'Tradução e Interpretação'),
    ('Administração de banco de dados', 'Banco de Dados'),
    ('Administração de medicamentos', 'Enfermagem'),
    ('Administração de redes', 'Infraestrutura de TI'),
    ('Adubação e fertilidade', 'Agronomia e Engenharia Agrícola'),
    ('Afinação de instrumentos', 'Luthieria e Instrumentos Musicais'),
    ('Agendamento', 'Atendimento ao Público e Recepção'),
    ('Agilidade', 'Bombeiros Civis e Salva-Vidas'),
    ('Agilidade', 'Caixas e Bilheteiros'),
    ('Agilidade', 'Embalagem e Logística de Produção'),
    ('Agilidade', 'Entregadores e Motoboys'),
    ('Agilidade', 'Garçons e Atendimento em Bares e Restaurantes'),
    ('Agilidade', 'Lavanderia e Cuidado de Roupas'),
    ('Agricultura de precisão', 'Agronomia e Engenharia Agrícola'),
    ('Agronegócio', 'Agronomia e Engenharia Agrícola'),
    ('Ajuste de máquinas', 'Manutenção Mecânica Industrial'),
    ('Ajuste de máquinas', 'Metalurgia e Usinagem'),
    ('Ajuste de peças', 'Montagem de Máquinas e Motores'),
    ('Ajuste de peças', 'Técnicos em Metalmecânica'),
    ('Alimentação e cuidados básicos', 'Pecuária (Trabalhadores)'),
    ('Alinhamento e balanceamento', 'Manutenção Eletromecânica'),
    ('Amor por animais', 'Cuidado de Animais de Estimação'),
    ('Anatomia aplicada', 'Fisioterapia'),
    ('Análise comportamental', 'Psicologia e Ciências Sociais'),
    ('Análise contábil', 'Contabilidade'),
    ('Análise de concorrência', 'Marketing e Publicidade'),
    ('Análise de conformidade', 'Fiscalização e Auditoria Pública'),
    ('Análise de crédito', 'Serviços Bancários e Financeiros'),
    ('Análise de cultivos', 'Agronomia e Engenharia Agrícola'),
    ('Análise de custos de frete', 'Logística e Transportes (Técnicos e Especialistas)'),
    ('Análise de dados', 'Matemática, Estatística e Ciência de Dados'),
    ('Análise de dados', 'Pesquisa Científica'),
    ('Análise de eficiência', 'Gestão Industrial e de Operações'),
    ('Análise de evidências', 'Delegacia de Polícia e Inteligência'),
    ('Análise de evidências', 'Perícia Criminal'),
    ('Análise de impacto ambiental', 'Engenharia Ambiental'),
    ('Análise de indicadores económicos', 'Mercado de Capitais e Investimentos'),
    ('Análise de investimentos', 'Finanças e Controladoria'),
    ('Análise de investimentos', 'Mercado de Capitais e Investimentos'),
    ('Análise de materiais', 'Engenharia Mecânica'),
    ('Análise de metas comerciais', 'Vendas e Comércio (Gestão)'),
    ('Análise de métricas', 'Marketing Digital e Mídias Sociais'),
    ('Análise de qualidade da água', 'Tratamento e Distribuição de Água e Esgoto'),
    ('Análise de riscos', 'Segurança Corporativa e Gestão de Riscos'),
    ('Análise de viabilidade', 'Pesquisa, Desenvolvimento e Inovação'),
    ('Análise de vulnerabilidades', 'Cibersegurança'),
    ('Análise financeira', 'Finanças e Controladoria'),
    ('Análise geológica', 'Mineração e Geologia'),
    ('Análise laboratorial', 'Engenharia Química'),
    ('Análise laboratorial', 'Engenharia de Alimentos'),
    ('Análise laboratorial', 'Física, Química e Ciências Naturais'),
    ('Análise processual', 'Ministério Público, Magistratura e Defensoria'),
    ('Análise técnica', 'Engenharia Elétrica e Eletrônica'),
    ('Análise técnica', 'Engenharia de Materiais e Metalurgia'),
    ('Análises laboratoriais', 'Biologia e Biomedicina'),
    ('Análises laboratoriais', 'Bioquímica e Biotecnologia'),
    ('Análises laboratoriais', 'Técnicos em Diagnóstico por Imagem e Laboratório'),
    ('Análises laboratoriais', 'Técnicos em Laboratório'),
    ('Análises laboratoriais', 'Técnicos em Química e Física'),
    ('Anúncios online', 'Marketing Digital e Mídias Sociais'),
    ('Aplicativos de entrega', 'Entregadores e Motoboys'),
    ('Aplicação de multas e autuações', 'Segurança Pública Municipal e Trânsito'),
    ('Apoio emocional', 'Apoio e Cuidados em Saúde'),
    ('Aprendizado continuo', 'TI (Geral/Outras Especialidades)'),
    ('Apresentação de pratos', 'Gastronomia e Culinária'),
    ('Apresentação de projetos', 'Marketing e Publicidade'),
    ('Apresentação de resultados', 'Pesquisa Científica'),
    ('Apresentação do produto', 'Produção Artesanal de Alimentos'),
    ('Apuração de fatos', 'Jornalismo e Mídia'),
    ('Argumentação', 'Ministério Público, Magistratura e Defensoria'),
    ('Argumentação de vendas', 'Telemarketing e Televendas'),
    ('Argumentação jurídica', 'Advocacia e Direito'),
    ('Arquivamento', 'Serviços Administrativos e Escritório'),
    ('Articulação política', 'Política e Administração Pública (Executivo, Legislativo e Judiciário)'),
    ('Atendimento', 'Secretariado Executivo'),
    ('Atendimento', 'Serviços Administrativos e Escritório'),
    ('Atendimento a chamados', 'Manutenção Predial (Reparos e Estruturas)'),
    ('Atendimento a chamados técnicos', 'Manutenção Eletroeletrônica'),
    ('Atendimento a chamados técnicos', 'Manutenção Eletromecânica'),
    ('Atendimento a chamados técnicos', 'Manutenção Industrial'),
    ('Atendimento a chamados técnicos', 'Manutenção Mecânica Industrial'),
    ('Atendimento a chamados técnicos', 'Manutenção de Equipamentos (Outros)'),
    ('Atendimento a chamados técnicos', 'Manutenção de Máquinas Pesadas e Agrícolas'),
    ('Atendimento a chamados técnicos', 'Telecomunicações e Eletroeletrônica'),
    ('Atendimento a chamados técnicos', 'Técnicos em Mecatrônica e Eletromecânica'),
    ('Atendimento a clientes', 'Advocacia e Direito'),
    ('Atendimento a clientes', 'Mercado de Capitais e Investimentos'),
    ('Atendimento a clientes', 'Serviços Bancários e Financeiros'),
    ('Atendimento a familias', 'Serviços Funerários'),
    ('Atendimento ao cliente', 'Atendimento ao Público e Recepção'),
    ('Atendimento ao cliente', 'Beleza e Estética'),
    ('Atendimento ao cliente', 'Caixas e Bilheteiros'),
    ('Atendimento ao cliente', 'Comércio'),
    ('Atendimento ao cliente', 'Design de Interiores'),
    ('Atendimento ao cliente', 'Elétrica Residencial e Predial'),
    ('Atendimento ao cliente', 'Entregadores e Motoboys'),
    ('Atendimento ao cliente', 'Farmácia'),
    ('Atendimento ao cliente', 'Garçons e Atendimento em Bares e Restaurantes'),
    ('Atendimento ao cliente', 'Gesso e Drywall'),
    ('Atendimento ao cliente', 'Hidráulica e Encanamento'),
    ('Atendimento ao cliente', 'Instalação e Manutenção de Ar-Condicionado'),
    ('Atendimento ao cliente', 'Joalheria e Ourivesaria'),
    ('Atendimento ao cliente', 'Manutenção Automotiva'),
    ('Atendimento ao cliente', 'Montagem de Móveis'),
    ('Atendimento ao cliente', 'Outros Serviços Diversos'),
    ('Atendimento ao cliente', 'Pintura Predial e Residencial'),
    ('Atendimento ao cliente', 'Relojoaria e Instrumentos de Precisão'),
    ('Atendimento ao cliente', 'Telemarketing e Televendas'),
    ('Atendimento ao cliente', 'Turismo, Hotelaria e Eventos'),
    ('Atendimento ao cliente', 'Vendas Ambulantes e a Domicilio'),
    ('Atendimento ao hóspede', 'Hotelaria e Hospedagem'),
    ('Atendimento ao paciente', 'Medicina'),
    ('Atendimento ao paciente', 'Odontologia'),
    ('Atendimento ao paciente', 'Técnicos em Diagnóstico por Imagem e Laboratório'),
    ('Atendimento ao paciente', 'Técnicos em Saúde'),
    ('Atendimento ao passageiro', 'Motoristas de Ônibus e Transporte Coletivo'),
    ('Atendimento ao público', 'Atendimento e Fiscalização em Transporte Coletivo'),
    ('Atendimento ao público', 'Biblioteconomia e Arquivologia'),
    ('Atendimento ao público', 'Correios, Documentação e Arquivo'),
    ('Atendimento ao público', 'Guia de Turismo e Condução de Excursões'),
    ('Atendimento ao público', 'Portaria e Zeladoria'),
    ('Atendimento ao público', 'Segurança Pública Municipal e Trânsito'),
    ('Atendimento ao usuário', 'Suporte Técnico de TI'),
    ('Atenção a detalhes', 'Artesanato'),
    ('Atenção a detalhes', 'Atendimento e Fiscalização em Transporte Coletivo'),
    ('Atenção a detalhes', 'Biblioteconomia e Arquivologia'),
    ('Atenção a detalhes', 'Biologia e Biomedicina'),
    ('Atenção a detalhes', 'Bioquímica e Biotecnologia'),
    ('Atenção a detalhes', 'Caixas e Bilheteiros'),
    ('Atenção a detalhes', 'Celulose e Papel'),
    ('Atenção a detalhes', 'Cerâmica, Vidro e Materiais de Construção'),
    ('Atenção a detalhes', 'Confecção de Artefatos de Tecido e Couro'),
    ('Atenção a detalhes', 'Confecção de Calçados'),
    ('Atenção a detalhes', 'Confecção de Roupas'),
    ('Atenção a detalhes', 'Contabilidade'),
    ('Atenção a detalhes', 'Correios, Documentação e Arquivo'),
    ('Atenção a detalhes', 'Couro e Peles'),
    ('Atenção a detalhes', 'Cultura e Produção de Eventos'),
    ('Atenção a detalhes', 'Desenho Técnico e Modelagem'),
    ('Atenção a detalhes', 'Elétrica Residencial e Predial'),
    ('Atenção a detalhes', 'Embalagem e Logística de Produção'),
    ('Atenção a detalhes', 'Farmácia'),
    ('Atenção a detalhes', 'Fiscalização e Auditoria Pública'),
    ('Atenção a detalhes', 'Fotografia'),
    ('Atenção a detalhes', 'Gastronomia e Culinária'),
    ('Atenção a detalhes', 'Instalação e Manutenção de Redes e Cabos'),
    ('Atenção a detalhes', 'Lavanderia e Cuidado de Roupas'),
    ('Atenção a detalhes', 'Limpeza e Conservação de Áreas'),
    ('Atenção a detalhes', 'Logística e Transportes (Técnicos e Especialistas)'),
    ('Atenção a detalhes', 'Luthieria e Instrumentos Musicais'),
    ('Atenção a detalhes', 'Manutenção de Equipamentos (Outros)'),
    ('Atenção a detalhes', 'Montagem Eletroeletrônica'),
    ('Atenção a detalhes', 'Navegação Marítima e Aviação'),
    ('Atenção a detalhes', 'Operação de Guindastes e Movimentação de Cargas'),
    ('Atenção a detalhes', 'Operação de Robôs e Equipamentos Especiais'),
    ('Atenção a detalhes', 'Produção Artesanal de Alimentos'),
    ('Atenção a detalhes', 'Produção Gráfica e Impressão'),
    ('Atenção a detalhes', 'Produção de Alimentos e Bebidas'),
    ('Atenção a detalhes', 'Produção de Fumo'),
    ('Atenção a detalhes', 'Relojoaria e Instrumentos de Precisão'),
    ('Atenção a detalhes', 'Segurança Corporativa e Gestão de Riscos'),
    ('Atenção a detalhes', 'Segurança Privada e Vigilância'),
    ('Atenção a detalhes', 'Serviços Administrativos e Escritório'),
    ('Atenção a detalhes', 'Tradução e Interpretação'),
    ('Atenção a detalhes', 'Transporte Aquaviário'),
    ('Atenção a detalhes', 'Transporte Ferroviário e Metroviário'),
    ('Atenção a detalhes', 'Técnicos em Diagnóstico por Imagem e Laboratório'),
    ('Atenção a detalhes', 'Têxtil, Vestuário e Calçados'),
    ('Atenção a detalhes', 'Visual Merchandising e Vitrinismo')
) AS v(habilidade_nome, area_nome)
JOIN emp_habilidades h ON h.nome = v.habilidade_nome
JOIN area_atuacao a ON a.nome = v.area_nome
ON CONFLICT (id_habilidade, id_area_atuacao) DO NOTHING;

-- 3. Extensões e Função
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE OR REPLACE FUNCTION immutable_unaccent(text)
RETURNS text AS $$
    SELECT public.unaccent($1);
$$ LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT;

-- 4. Índices
CREATE INDEX IF NOT EXISTS idx_emp_habilidades_nome_unaccent_trgm 
ON emp_habilidades 
USING gin (lower(immutable_unaccent(nome)) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_area_atuacao_nome_unaccent_trgm 
ON area_atuacao 
USING gin (lower(immutable_unaccent(nome)) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_habilidade_area 
ON area_atuacao_habilidade (id_area_atuacao);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- 1. Remoção das Tabelas (O DROP TABLE remove automaticamente seus índices e constraints)
DROP TABLE IF EXISTS area_atuacao_habilidade;
DROP TABLE IF EXISTS area_atuacao;
DROP TABLE IF EXISTS emp_habilidades;

-- 2. Remoção da Função
DROP FUNCTION IF EXISTS immutable_unaccent(text);

-- +goose StatementEnd